### ISSUE TITLE
读取语料时编码错误

### ISSUE THREAD

**Issue by cjdxhjj** [yansh97/jieba3#2]
![image](https://github.com/user-attachments/assets/86b6475b-152c-42a7-98d0-dd8098220cc6)
python 3.12

**Comment by yansh97** [comment]
感谢指出问题，请尝试在报错处（jieba3/tok.py，第26行）的`read_text()`添加参数，更改为`read_text(encoding="utf-8")`作为临时方案，如果没有问题，我会更新一个bugfix版本

**Comment by cjdxhjj** [comment]
对，windows的默认字符集不是utf-8

**Comment by cjdxhjj** [comment]
也可以先检测一下文件的charset

**Comment by cjdxhjj** [comment]
另外能否将读取那个文件做个缓存或仅初始化一次，每次导入都读取一遍那些文件

**Comment by cjdxhjj** [comment]
@yansh97

**Comment by yansh97** [comment]
> 另外能否将读取那个文件做个缓存或仅初始化一次，每次导入都读取一遍那些文件

Python会自动缓存导入的结果，在同一个进程里多次导入，只会执行一次的

**Comment by cjdxhjj** [comment]
![image](https://github.com/user-attachments/assets/615f65f6-9bca-450f-b14d-908d72fae9df)
虽然我只用basic,但是small,large的也会读取

**Comment by cjdxhjj** [comment]
哦，我对python不太熟，目前我包装了一个类，只导入一次jieba

**Comment by cjdxhjj** [comment]
![image](https://github.com/user-attachments/assets/e5115669-f182-4900-ad65-83c742119ce1)

**Comment by yansh97** [comment]
> 哦，我对python不太熟，目前我包装了一个类，只导入一次jieba

这个没事的，在整个进程里无论导入几次只会读取一次，且只会保存一份在内存中，所以不会影响的。读取额外的模型带来的额外内存不会超过100M，暂时就没优化。

**Comment by cjdxhjj** [comment]
好的

**Comment by yansh97** [comment]
> 感谢指出问题，请尝试在报错处（jieba3/tok.py，第26行）的`read_text()`添加参数，更改为`read_text(encoding="utf-8")`作为临时方案，如果没有问题，我会更新一个bugfix版本

已经修改并在pypi上发布了1.0.2版本，可以更新下。如果没问题我就关闭issue了。

**Comment by cjdxhjj** [comment]
好的，我试下

**Comment by cjdxhjj** [comment]
可以了

**Comment by yansh97** [comment]
> 可以了

👌
